import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

const workbenchBasePlugin = plugin(({ addBase }) => {
  addBase({
    ':root': {
      '--nomi-bg': 'oklch(0.985 0.003 90)',
      '--nomi-paper': 'oklch(1 0 0)',
      '--nomi-ink': 'oklch(0.22 0.01 80)',
      '--nomi-ink-80': 'oklch(0.32 0.01 80)',
      '--nomi-ink-60': 'oklch(0.50 0.01 80)',
      '--nomi-ink-40': 'oklch(0.68 0.01 80)',
      '--nomi-ink-30': 'oklch(0.78 0.01 80)',
      '--nomi-ink-20': 'oklch(0.88 0.005 80)',
      '--nomi-ink-10': 'oklch(0.94 0.003 80)',
      '--nomi-ink-05': 'oklch(0.97 0.003 80)',
      '--nomi-line': 'oklch(0.91 0.004 80)',
      '--nomi-line-soft': 'oklch(0.95 0.003 80)',
      '--nomi-accent': 'oklch(0.55 0.13 250)',
      '--nomi-accent-soft': 'color-mix(in oklch, var(--nomi-accent) 12%, var(--nomi-paper))',
      // 全局焦点环色（accent 42%）。所有交互控件 :focus-visible 统一用它，覆盖 macOS 系统强调色的
      // outline:auto（用户设了橙/黄就冒橙环）。全局 :root → portal 到 body 的面板也生效。
      '--nomi-focus': 'color-mix(in srgb, var(--nomi-accent) 42%, transparent)',
      '--nomi-track-text': 'var(--nomi-accent)',
      '--nomi-track-image': 'oklch(0.7 0.13 200)',
      '--nomi-track-video': 'oklch(0.65 0.13 150)',
      '--nomi-snap': 'oklch(0.72 0.18 30)',
      '--nomi-snap-tag': 'oklch(0.45 0.18 30)',
      // 3D 轴向语义色(X/Y/Z)。主题无关——明暗两模式同色（用户拍板：3D 渲染色不动）。
      '--nomi-axis-x': '#ef4444',
      '--nomi-axis-y': '#16a34a',
      '--nomi-axis-z': '#3b82f6',
      // 媒体浮层（图上 scrim / 徽章 / 底部标题渐变）。此前仅存于未加载的 nomi-tokens.css → 运行时 undefined，
      // 现补进真源（live = 本 addBase），消费点：提示词库/技能库/库页 scrim、引导旅途背景。
      '--nomi-scrim': 'oklch(0.2 0.01 80 / 0.42)',
      '--nomi-overlay-chip': 'oklch(0.2 0.01 80 / 0.55)',
      '--nomi-overlay-chip-strong': 'oklch(0.2 0.01 80 / 0.7)',
      '--nomi-media-veil': 'oklch(0.15 0.01 80 / 0.62)',
      '--nomi-shadow-sm': '0 1px 2px oklch(0 0 0 / 0.04), 0 1px 1px oklch(0 0 0 / 0.03)',
      '--nomi-shadow-md': '0 2px 4px oklch(0 0 0 / 0.04), 0 8px 24px oklch(0 0 0 / 0.06)',
      '--nomi-shadow-lg': '0 4px 8px oklch(0 0 0 / 0.05), 0 20px 50px oklch(0 0 0 / 0.08)',
      '--nomi-radius-sm': '6px',
      '--nomi-radius': '10px',
      '--nomi-radius-lg': '16px',
      '--nomi-transition-fast': '140ms cubic-bezier(.2, .7, .3, 1)',
      '--nomi-font-sans': 'Inter, -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", system-ui, sans-serif',
      '--nomi-font-display': 'Fraunces, Inter, serif',
      '--nomi-font-mono': 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace',
      'color-scheme': 'light',
      '--tc-radius-sharp': '0px',
      '--tc-radius-field': '6px',
      '--tc-radius-panel': '10px',
      '--tc-radius-modal': '14px',
      '--tc-radius-pill': '999px',
      '--tc-space-1': '4px',
      '--tc-space-2': '8px',
      '--tc-space-3': '12px',
      '--tc-space-4': '16px',
      '--tc-space-5': '20px',
      '--tc-space-6': '24px',
      '--tc-font-size-body': '14px',
      '--tc-font-size-body-sm': '13px',
      '--tc-font-size-caption': '12px',
      '--tc-font-size-title': '16px',
      '--handle-hit-outside': '20px',
      '--handle-hit-inside': '8px',
      '--handle-hit-vertical': '18px',
      '--handle-color-image': '#7dd3fc',
      '--handle-color-audio': '#34d399',
      '--handle-color-subtitle': '#facc15',
      '--handle-color-video': '#c084fc',
      '--handle-color-character': '#f472b6',
      '--handle-color-any': '#94a3b8',
      '--handle-surface': 'rgba(4, 7, 18, 0.88)',
      '--handle-border': 'rgba(255, 255, 255, 0.42)',
      '--tc-snap-outline': 'rgba(147, 197, 253, 0.55)',
      '--tc-snap-shadow': '0 0 0 3px rgba(147, 197, 253, 0.7), 0 0 30px rgba(147, 197, 253, 0.35)',
      '--tc-gen-overlay-bg': 'rgba(255, 255, 255, 0.07)',
      '--tc-gen-overlay-border': 'rgba(255, 255, 255, 0.10)',
      '--tc-gen-overlay-sheen': 'rgba(255, 255, 255, 0.28)',
      '--tc-gen-overlay-body-from': 'rgba(0, 0, 0, 0.35)',
      '--tc-gen-overlay-body-to': 'rgba(0, 0, 0, 0.05)',
      '--tc-gen-overlay-text': 'rgba(255, 255, 255, 0.85)',
      '--tc-color-app-bg': '#05070b',
      '--tc-color-app-bg-strong': '#020409',
      '--tc-color-surface': '#0b0f14',
      '--tc-color-surface-raised': '#10161d',
      '--tc-color-surface-subtle': '#131a22',
      '--tc-color-surface-inline': 'rgba(255, 255, 255, 0.035)',
      '--tc-color-surface-inline-weak': 'rgba(255, 255, 255, 0.03)',
      '--tc-color-border-subtle': 'rgba(226, 232, 240, 0.08)',
      '--tc-color-border-strong': 'rgba(125, 211, 252, 0.24)',
      '--tc-color-text-primary': '#edf3ff',
      '--tc-color-text-secondary': '#aab7ca',
      '--tc-color-text-tertiary': '#73839a',
      '--tc-color-accent-blue': '#60a5fa',
      '--tc-color-accent-cyan': '#22d3ee',
      '--tc-color-success': '#34d399',
      '--tc-color-warning': '#fbbf24',
      '--tc-color-danger': '#f87171',
      '--tc-color-info': '#38bdf8',
    },
    ':root[data-mantine-color-scheme="light"]': {
      '--handle-color-image': '#2563eb',
      '--handle-color-audio': '#0d9488',
      '--handle-color-subtitle': '#ca8a04',
      '--handle-color-video': '#7c3aed',
      '--handle-color-character': '#db2777',
      '--handle-color-any': '#475569',
      '--handle-surface': 'rgba(255, 255, 255, 0.96)',
      '--handle-border': 'rgba(15, 23, 42, 0.2)',
      '--tc-snap-outline': 'rgba(37, 99, 235, 0.22)',
      '--tc-snap-shadow': '0 0 0 3px rgba(37, 99, 235, 0.18), 0 0 26px rgba(37, 99, 235, 0.12)',
      '--tc-gen-overlay-bg': 'rgba(15, 23, 42, 0.05)',
      '--tc-gen-overlay-border': 'rgba(15, 23, 42, 0.10)',
      '--tc-gen-overlay-sheen': 'rgba(15, 23, 42, 0.10)',
      '--tc-gen-overlay-body-from': 'rgba(255, 255, 255, 0.85)',
      '--tc-gen-overlay-body-to': 'rgba(255, 255, 255, 0.35)',
      '--tc-gen-overlay-text': 'rgba(15, 23, 42, 0.72)',
    },
    // ── 深色主题（暖灰 oklch，与浅色同色相、低明度反转）。token-only → 翻这一组即翻全局。
    //    3D 轴色(--nomi-axis-*)刻意不覆盖：主题无关的渲染语义色，明暗同色（用户拍板）。
    ':root[data-mantine-color-scheme="dark"]': {
      'color-scheme': 'dark',
      '--nomi-bg': 'oklch(0.18 0.006 80)',
      '--nomi-paper': 'oklch(0.235 0.007 80)',
      '--nomi-ink': 'oklch(0.93 0.006 85)',
      '--nomi-ink-80': 'oklch(0.84 0.006 85)',
      '--nomi-ink-60': 'oklch(0.70 0.006 85)',
      '--nomi-ink-40': 'oklch(0.56 0.006 85)',
      '--nomi-ink-30': 'oklch(0.44 0.006 85)',
      '--nomi-ink-20': 'oklch(0.36 0.006 85)',
      '--nomi-ink-10': 'oklch(0.30 0.006 85)',
      '--nomi-ink-05': 'oklch(0.27 0.006 85)',
      '--nomi-line': 'oklch(0.36 0.007 80)',
      '--nomi-line-soft': 'oklch(0.31 0.007 80)',
      '--nomi-accent': 'oklch(0.70 0.13 250)',
      '--nomi-accent-soft': 'color-mix(in oklch, var(--nomi-accent) 18%, var(--nomi-paper))',
      '--nomi-focus': 'color-mix(in srgb, var(--nomi-accent) 50%, transparent)',
      // 时间轴三轨：暗底提亮以保持可辨（fork 未覆盖，本次补）。
      '--nomi-track-text': 'oklch(0.75 0.15 305)',
      '--nomi-track-image': 'oklch(0.72 0.13 200)',
      '--nomi-track-video': 'oklch(0.70 0.13 150)',
      '--nomi-snap': 'oklch(0.78 0.18 30)',
      '--nomi-snap-tag': 'oklch(0.62 0.18 30)',
      '--nomi-scrim': 'oklch(0.08 0.004 80 / 0.58)',
      '--nomi-overlay-chip': 'oklch(0.08 0.004 80 / 0.68)',
      '--nomi-overlay-chip-strong': 'oklch(0.08 0.004 80 / 0.78)',
      '--nomi-media-veil': 'oklch(0.08 0.004 80 / 0.76)',
      '--nomi-shadow-sm': '0 1px 2px oklch(0 0 0 / 0.32), 0 1px 1px oklch(0 0 0 / 0.22)',
      '--nomi-shadow-md': '0 2px 5px oklch(0 0 0 / 0.30), 0 14px 34px oklch(0 0 0 / 0.32)',
      '--nomi-shadow-lg': '0 4px 10px oklch(0 0 0 / 0.30), 0 24px 64px oklch(0 0 0 / 0.40)',
    },
    '*': {
      'box-sizing': 'border-box',
    },
    // 全局焦点环根治（P2）：默认杀掉浏览器 :focus-visible 的 outline:auto（macOS 跟系统强调色＝橙环），
    // 交互控件统一用 accent 环。没人需要再往按钮上记着加 className——漏一个就冒橙环的问题从根上没了。
    // 编辑器（contenteditable，非 button）不吃 ring；其 workbench.css 的 outline:none 仍是防御性覆盖。
    ':focus-visible': {
      outline: 'none',
    },
    'button:focus-visible, [role="button"]:focus-visible, a:focus-visible, input:focus-visible, select:focus-visible, textarea:focus-visible, summary:focus-visible': {
      outline: '2px solid var(--nomi-focus)',
      'outline-offset': '2px',
    },
    'html, body, #root': {
      width: '100%',
      height: '100%',
      background: 'var(--nomi-bg)',
    },
    'html, body': {
      'overscroll-behavior': 'none',
      'scrollbar-gutter': 'stable',
    },
    body: {
      margin: '0',
      'min-height': '100%',
      'font-family': "'Inter', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      'background-color': 'var(--tc-color-app-bg)',
      'background-image':
        'radial-gradient(circle at 18% 14%, rgba(34,211,238,0.07), transparent 32%), radial-gradient(circle at 82% 0%, rgba(96,165,250,0.06), transparent 28%), linear-gradient(180deg, var(--tc-color-app-bg-strong) 0%, var(--tc-color-app-bg) 52%, #06090f 100%)',
      color: 'var(--mantine-color-text, var(--tc-color-text-primary))',
    },
    ':root[data-mantine-color-scheme="light"] body': {
      'background-color': '#f7f9ff',
      'background-image':
        'radial-gradient(circle at 10% 15%, rgba(59,130,246,0.12), transparent 55%), radial-gradient(circle at 85% -5%, rgba(14,165,233,0.12), transparent 45%), linear-gradient(180deg, #f7f9ff 0%, #ecf2ff 55%, #e4ebfb 100%)',
      color: 'var(--mantine-color-text, #111321)',
    },
    // 深色 body：覆盖默认那套旧蓝黑 --tc-color-app-bg 渐变，换成暖灰 --nomi-bg（否则 dark 会掉回休眠旧主题）。
    ':root[data-mantine-color-scheme="dark"] body': {
      'background-color': 'var(--nomi-bg)',
      'background-image': 'linear-gradient(180deg, oklch(0.19 0.006 80) 0%, var(--nomi-bg) 100%)',
      color: 'var(--mantine-color-text, var(--nomi-ink))',
    },
    '#root': {
      position: 'relative',
      isolation: 'isolate',
    },
    '#root::before': {
      content: "''",
      position: 'absolute',
      inset: '0',
      'pointer-events': 'none',
      'background-image':
        'linear-gradient(120deg, rgba(255,255,255,0.026) 1px, transparent 1px), linear-gradient(0deg, rgba(255,255,255,0.026) 1px, transparent 1px)',
      'background-size': '60px 60px',
      opacity: '0.08',
      'z-index': '-1',
    },
    ':root[data-mantine-color-scheme="light"] #root::before': {
      opacity: '0.08',
    },
    '.nomi-loading-mark__logo': {
      display: 'block',
      width: 'var(--nomi-loading-size, 18px)',
      height: 'var(--nomi-loading-size, 18px)',
    },
    '.mantine-Tooltip-tooltip': {
      'white-space': 'nowrap !important',
      'word-break': 'normal !important',
      'overflow-wrap': 'normal !important',
      'max-width': 'min(80vw, 520px)',
      overflow: 'hidden',
      'text-overflow': 'ellipsis',
    },
    '.tc-panel-card .mantine-Paper-root[data-with-border], .tc-panel-card .mantine-Card-root[data-with-border], .mantine-Paper-root[data-with-border] .mantine-Paper-root[data-with-border], .mantine-Paper-root[data-with-border] .mantine-Card-root[data-with-border], .mantine-Card-root[data-with-border] .mantine-Paper-root[data-with-border], .mantine-Card-root[data-with-border] .mantine-Card-root[data-with-border]': {
      'border-radius': '0 !important',
      'border-color': 'transparent !important',
      'box-shadow': 'none !important',
      background: 'var(--tc-color-surface-inline) !important',
    },
    '.mantine-Button-root[data-variant="subtle"]': {
      background: 'transparent !important',
    },
    '.asset-panel-shell .mantine-Button-root': {
      'min-height': '22px',
      'padding-inline': '8px',
    },
    '.asset-panel-shell .mantine-ActionIcon-root': {
      width: '22px',
      'min-width': '22px',
      height: '22px',
    },
    '.asset-panel-shell .mantine-SegmentedControl-root': {
      'min-height': '22px',
    },
    '.asset-panel-shell .mantine-SegmentedControl-label': {
      'min-height': '20px',
      'padding-inline': '7px',
    },
    '.asset-panel-shell .mantine-Tabs-tab': {
      'min-height': '24px',
      padding: '0 8px',
    },
    '.asset-panel-shell .mantine-Badge-root': {
      'min-height': '16px',
      'padding-inline': '6px',
    },
    '.asset-panel-shell .mantine-Input-input, .asset-panel-shell .mantine-Select-input': {
      'min-height': '24px',
      'padding-inline': '8px',
    },
    '.ai-character-library-root .mantine-ActionIcon-root, .ai-character-library-detail-root .mantine-ActionIcon-root': {
      width: '24px',
      'min-width': '24px',
      height: '24px',
    },
    '.ai-character-library-root .mantine-Input-input, .ai-character-library-detail-root .mantine-Input-input': {
      'min-height': '24px',
    },
    ':root[data-mantine-color-scheme="light"] .mantine-AppShell-main': {
      background:
        'radial-gradient(circle at 15% 15%, rgba(59,130,246,0.15), transparent 45%), radial-gradient(circle at 80% 0%, rgba(14,165,233,0.12), transparent 40%), var(--mantine-color-body) !important',
    },
    ':root[data-mantine-color-scheme="light"] .mantine-AppShell-header, :root[data-mantine-color-scheme="light"] .mantine-AppShell-navbar, :root[data-mantine-color-scheme="light"] .mantine-AppShell-aside': {
      background: 'rgba(255, 255, 255, 0.86) !important',
      border: 'none !important',
      'box-shadow': '0 18px 40px rgba(15, 23, 42, 0.12)',
      'backdrop-filter': 'blur(10px)',
      '-webkit-backdrop-filter': 'blur(10px)',
    },
    ':root[data-mantine-color-scheme="light"] .mantine-Button-root[data-variant="outline"]': {
      border: 'none !important',
      background: 'rgba(59, 130, 246, 0.06) !important',
      'box-shadow': '0 10px 20px rgba(15, 23, 42, 0.08)',
    },
    ':root[data-mantine-color-scheme="light"] .mantine-Button-root[data-variant="outline"]:hover': {
      border: 'none !important',
      background: 'rgba(59, 130, 246, 0.12) !important',
    },
    ':root[data-mantine-color-scheme="light"] .mantine-Button-root[data-variant="light"]': {
      border: 'none !important',
      background: 'rgba(15, 23, 42, 0.03) !important',
    },
    ':root[data-mantine-color-scheme="light"] .mantine-Button-root[data-variant="light"]:hover': {
      border: 'none !important',
      background: 'rgba(15, 23, 42, 0.05) !important',
    },
    ':root[data-mantine-color-scheme="light"] .mantine-Paper-root[data-with-border]:not(.template-panel-shell):not(.template-panel-card):not(.template-space):not(.template-detail)': {
      border: 'none !important',
      'box-shadow': '0 15px 40px rgba(15, 23, 42, 0.08)',
    },
    ':root[data-mantine-color-scheme="light"] *::-webkit-scrollbar': {
      width: '8px',
      height: '8px',
    },
    ':root[data-mantine-color-scheme="light"] *::-webkit-scrollbar-thumb': {
      background: 'rgba(15, 23, 42, 0.14)',
      'border-radius': '8px',
    },
    ':root[data-mantine-color-scheme="light"] *::-webkit-scrollbar-thumb:hover': {
      background: 'rgba(15, 23, 42, 0.25)',
    },
    ':root[data-mantine-color-scheme="light"] *::-webkit-scrollbar-track': {
      background: 'transparent',
    },
    ':root[data-mantine-color-scheme="light"] [data-ux-panel]': {
      'scrollbar-width': 'thin',
      'scrollbar-color': 'rgba(15, 23, 42, 0.25) transparent',
    },
    ':root[data-mantine-color-scheme="light"] [data-ux-panel] *::-webkit-scrollbar': {
      width: '6px',
      height: '6px',
    },
    ':root[data-mantine-color-scheme="light"] [data-ux-panel] *::-webkit-scrollbar-thumb': {
      background: 'rgba(15, 23, 42, 0.2)',
      'border-radius': '8px',
    },
    ':root[data-mantine-color-scheme="light"] [data-ux-panel] *::-webkit-scrollbar-thumb:hover': {
      background: 'rgba(15, 23, 42, 0.35)',
    },
    ':root[data-mantine-color-scheme="light"] [data-ux-panel] *::-webkit-scrollbar-track': {
      background: 'transparent',
    },
    '[data-compact="true"] .mantine-Button-root': {
      padding: '4px 8px !important',
    },
    '[data-compact="true"] .mantine-NumberInput-input, [data-compact="true"] .mantine-TextInput-input, [data-compact="true"] textarea': {
      padding: '6px 8px !important',
    },
    '[data-compact="true"] .mantine-Stack-root': {
      gap: '6px !important',
    },
    '[data-compact="true"] .mantine-Group-root': {
      gap: '6px !important',
    },
    '.workbench-shell': {
      '--workbench-topbar-height': '56px',
      '--workbench-timeline-height': '188px',
      '--workbench-preview-timeline-height': '208px',
      '--workbench-timeline-label-width': '112px',
      '--workbench-bg': 'var(--nomi-bg)',
      '--workbench-surface': 'var(--nomi-paper)',
      '--workbench-surface-solid': 'var(--nomi-paper)',
      '--workbench-surface-soft': 'var(--nomi-ink-05)',
      '--workbench-border': 'var(--nomi-line)',
      '--workbench-border-soft': 'var(--nomi-line-soft)',
      '--workbench-border-strong': 'var(--nomi-ink-30)',
      '--workbench-muted': 'var(--nomi-ink-60)',
      '--workbench-muted-soft': 'var(--nomi-ink-40)',
      '--workbench-ink': 'var(--nomi-ink)',
      '--workbench-accent': 'var(--nomi-accent)',
      '--workbench-accent-soft': 'var(--nomi-accent-soft)',
      '--workbench-success': '#34c759',
      '--workbench-success-soft': 'rgba(52, 199, 89, 0.12)',
      '--workbench-danger': '#ff3b30',
      '--workbench-danger-soft': 'rgba(255, 59, 48, 0.1)',
      '--workbench-video': '#00a886',
      '--workbench-video-soft': 'rgba(0, 168, 134, 0.11)',
      '--workbench-success-ink': '#248a3d',
      '--workbench-hover': 'rgba(60, 60, 67, 0.06)',
      '--workbench-pressed': 'rgba(60, 60, 67, 0.09)',
      '--workbench-overlay': 'rgba(255, 255, 255, 0.82)',
      '--workbench-overlay-strong': 'rgba(255, 255, 255, 0.94)',
      '--workbench-backdrop': 'rgba(29, 29, 31, 0.16)',
      '--workbench-code-bg': '#1d1d1f',
      '--workbench-code-ink': '#f5f5f7',
      '--workbench-radius': 'var(--nomi-radius)',
      '--workbench-shadow-sm': 'var(--nomi-shadow-sm)',
      '--workbench-shadow-md': 'var(--nomi-shadow-md)',
      '--workbench-shadow-pop': 'var(--nomi-shadow-lg)',
      '--workbench-control-size': '32px',
      '--workbench-control-size-sm': '26px',
      '--workbench-control-radius': '7px',
      '--workbench-icon-size': '16px',
      '--workbench-icon-stroke': '2',
      '--canvas-surface-bg': 'var(--workbench-bg)',
      '--tc-spotlight-grid-color': 'rgba(60, 60, 67, 0.22)',
      '--workbench-ai-header-height': '60px',
      '--workbench-ai-composer-min-height': '112px',
      '--workbench-ai-panel-bg': 'var(--workbench-surface)',
      '--workbench-ai-message-bg': 'var(--workbench-surface)',
      '--workbench-ai-user-bg': 'var(--workbench-accent-soft)',
      '--workbench-ai-composer-bg': 'var(--workbench-surface-soft)',
      '--workbench-ai-border': 'var(--workbench-border-soft)',
      '--workbench-ai-border-strong': 'var(--workbench-border)',
      '--workbench-ai-radius': '8px',
      '--workbench-ai-control-radius': '7px',
    },
    '.workbench-editor__scroll > div': {
      'min-height': '100%',
      display: 'flex',
    },
    '.workbench-editor__scroll .ProseMirror, .workbench-editor__scroll .tiptap': {
      'min-height': '100%',
      width: '100%',
      'box-sizing': 'border-box',
    },
    '.workbench-editor__scroll, .workbench-creation-ai__messages': {
      'scrollbar-color': 'transparent transparent',
      'scrollbar-width': 'thin',
    },
    '.workbench-editor__scroll:hover, .workbench-editor__scroll:focus-within, .workbench-editor__scroll.workbench-scrollbar-visible, .workbench-creation-ai__messages:hover, .workbench-creation-ai__messages:focus-within, .workbench-creation-ai__messages.workbench-scrollbar-visible': {
      'scrollbar-color': 'color-mix(in srgb, var(--nomi-ink) 22%, transparent) transparent',
    },
    '.workbench-editor__scroll::-webkit-scrollbar, .workbench-creation-ai__messages::-webkit-scrollbar': {
      width: '0',
      height: '0',
    },
    '.workbench-editor__scroll:hover::-webkit-scrollbar, .workbench-editor__scroll:focus-within::-webkit-scrollbar, .workbench-editor__scroll.workbench-scrollbar-visible::-webkit-scrollbar, .workbench-creation-ai__messages:hover::-webkit-scrollbar, .workbench-creation-ai__messages:focus-within::-webkit-scrollbar, .workbench-creation-ai__messages.workbench-scrollbar-visible::-webkit-scrollbar': {
      width: '6px',
      height: '6px',
    },
    '.workbench-editor__scroll::-webkit-scrollbar-track, .workbench-creation-ai__messages::-webkit-scrollbar-track': {
      background: 'transparent',
    },
    '.workbench-editor__scroll::-webkit-scrollbar-thumb, .workbench-creation-ai__messages::-webkit-scrollbar-thumb': {
      'border-radius': '999px',
      background: 'transparent',
    },
    '.workbench-editor__scroll:hover::-webkit-scrollbar-thumb, .workbench-editor__scroll:focus-within::-webkit-scrollbar-thumb, .workbench-editor__scroll.workbench-scrollbar-visible::-webkit-scrollbar-thumb, .workbench-creation-ai__messages:hover::-webkit-scrollbar-thumb, .workbench-creation-ai__messages:focus-within::-webkit-scrollbar-thumb, .workbench-creation-ai__messages.workbench-scrollbar-visible::-webkit-scrollbar-thumb': {
      background: 'color-mix(in srgb, var(--nomi-ink) 18%, transparent)',
    },
  })
})

export default {
  content: [
    './index.html',
    './src/**/*.tsx',
    '!./src/**/*.test.tsx',
    '!./src/**/*.spec.tsx',
    '!./src/**/*.d.ts',
    '!./src/vendor/**',
  ],
  safelist: [
    'mantine-Tooltip-tooltip',
    'tc-panel-card',
    'mantine-Paper-root',
    'mantine-Card-root',
    'mantine-Button-root',
    'asset-panel-shell',
    'mantine-ActionIcon-root',
    'mantine-SegmentedControl-root',
    'mantine-SegmentedControl-label',
    'mantine-Tabs-tab',
    'mantine-Badge-root',
    'mantine-Input-input',
    'mantine-Select-input',
    'ai-character-library-root',
    'ai-character-library-detail-root',
    'mantine-AppShell-main',
    'mantine-AppShell-header',
    'mantine-AppShell-navbar',
    'mantine-AppShell-aside',
    'mantine-NumberInput-input',
    'mantine-TextInput-input',
    'mantine-Stack-root',
    'mantine-Group-root',
  ],
  darkMode: ['selector', '[data-mantine-color-scheme="dark"]'],
  theme: {
    extend: {
      colors: {
        // 旧 --tc-color-* 暗色层已删(§14.1)+ 4 个过渡键的最后消费者(PanoramaViewer/dead surfaces)
        // 已收口到 --nomi-* 类，过渡键随之删净。新增颜色一律进 nomi-tokens.css 的 --nomi-*。
        nomi: {
          bg: 'var(--nomi-bg)',
          paper: 'var(--nomi-paper)',
          ink: 'var(--nomi-ink)',
          'ink-80': 'var(--nomi-ink-80)',
          'ink-60': 'var(--nomi-ink-60)',
          'ink-40': 'var(--nomi-ink-40)',
          'ink-30': 'var(--nomi-ink-30)',
          'ink-20': 'var(--nomi-ink-20)',
          'ink-10': 'var(--nomi-ink-10)',
          'ink-05': 'var(--nomi-ink-05)',
          line: 'var(--nomi-line)',
          'line-soft': 'var(--nomi-line-soft)',
          accent: 'var(--nomi-accent)',
          'accent-soft': 'var(--nomi-accent-soft)',
          scrim: 'var(--nomi-scrim)',
          'overlay-chip': 'var(--nomi-overlay-chip)',
          'overlay-chip-strong': 'var(--nomi-overlay-chip-strong)',
          'media-veil': 'var(--nomi-media-veil)',
        },
        workbench: {
          bg: 'var(--workbench-bg)',
          surface: 'var(--workbench-surface)',
          'surface-solid': 'var(--workbench-surface-solid)',
          'surface-soft': 'var(--workbench-surface-soft)',
          border: 'var(--workbench-border)',
          'border-soft': 'var(--workbench-border-soft)',
          'border-strong': 'var(--workbench-border-strong)',
          ink: 'var(--workbench-ink)',
          muted: 'var(--workbench-muted)',
          'muted-soft': 'var(--workbench-muted-soft)',
          accent: 'var(--workbench-accent)',
          'accent-soft': 'var(--workbench-accent-soft)',
          success: 'var(--workbench-success)',
          'success-soft': 'var(--workbench-success-soft)',
          danger: 'var(--workbench-danger)',
          'danger-soft': 'var(--workbench-danger-soft)',
          hover: 'var(--workbench-hover)',
          pressed: 'var(--workbench-pressed)',
          overlay: 'var(--workbench-overlay)',
          backdrop: 'var(--workbench-backdrop)',
          'code-bg': 'var(--workbench-code-bg)',
          'code-ink': 'var(--workbench-code-ink)',
        },
      },
      borderRadius: {
        // 旧 --tc-radius-* 已删(§14.1)；恢复为字面值（与 nomiTheme.ts nomiDesignTokens.radius 一致）。
        sharp: '0px',
        field: '6px',
        panel: '10px',
        modal: '14px',
        pill: '999px',
        nomi: 'var(--nomi-radius)',
        'nomi-sm': 'var(--nomi-radius-sm)',
        'nomi-lg': 'var(--nomi-radius-lg)',
        workbench: 'var(--workbench-radius)',
        'workbench-control': 'var(--workbench-control-radius)',
      },
      fontSize: {
        // 旧 --tc-font-size-* 已删(§14.1)；恢复为字面值（与 nomiTheme.ts nomiDesignTokens.fontSize 一致）。
        // 仅 font-size、不带 line-height，与原 --tc-* 行为一致，避免改动既有布局。
        micro: '11px',
        body: '14px',
        'body-sm': '13px',
        caption: '12px',
        title: '16px',
        h2: '20px',
        h1: '24px',
        display: '28px',
      },
      fontFamily: {
        'nomi-sans': 'var(--nomi-font-sans)',
        'nomi-display': 'var(--nomi-font-display)',
        'nomi-mono': 'var(--nomi-font-mono)',
      },
      boxShadow: {
        'nomi-sm': 'var(--nomi-shadow-sm)',
        'nomi-md': 'var(--nomi-shadow-md)',
        'nomi-lg': 'var(--nomi-shadow-lg)',
        'workbench-sm': 'var(--workbench-shadow-sm)',
        'workbench-md': 'var(--workbench-shadow-md)',
        'workbench-pop': 'var(--workbench-shadow-pop)',
      },
      keyframes: {
        'generation-focus-pulse': {
          '0%': {
            filter: 'drop-shadow(0 0 0 rgba(80, 112, 255, 0))',
            transform: 'scale(1)',
          },
          '18%': {
            filter: 'drop-shadow(0 0 24px rgba(80, 112, 255, 0.42))',
            transform: 'scale(1.018)',
          },
          '100%': {
            filter: 'drop-shadow(0 0 0 rgba(80, 112, 255, 0))',
            transform: 'scale(1)',
          },
        },
      },
      animation: {
        'generation-focus-pulse': 'generation-focus-pulse 1.35s ease-out',
      },
      transitionTimingFunction: {
        'nomi-fast': 'var(--nomi-transition-fast)',
      },
    },
  },
  plugins: [workbenchBasePlugin],
} satisfies Config
